- name: Create standard ssd storage class
  kubernetes.core.k8s:
    state: present
    definition:
      kind: StorageClass
      apiVersion: storage.k8s.io/v1
      metadata:
        name: sc-hostpath
      provisioner: "{{var_provisioner}}/hostpath"
      reclaimPolicy: Delete
      parameters:
        pvDir: /opt/sc-hostpath
      volumeBindingMode: WaitForFirstConsumer