- name: Create common ingress
  kubernetes.core.k8s:
    state: present
    # state: absent
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: http-ingress
        namespace: wordpress
      spec:
        rules:
          - host: "{{var_wordpress_hostname}}.{{var_domain}}"
            http:
              paths:
              - pathType: Prefix
                path: "/"
                backend:
                  service:
                    name: wordpress
                    port:
                      number: 80
        ports:
          - name: mariadb
            port: 3306
            targetPort: 3306
            protocol: TCP

- name: Create common ingress
  kubernetes.core.k8s:
    state: present
    # state: absent
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: http-ingress
        namespace: velero
      spec:
        rules:
          - host: "{{var_minio_devel if ansible_env.K8S_AUTH_CONTEXT == 'devel' else var_minio_prod}}.{{var_domain}}"
            http:
              paths:
              - pathType: Prefix
                path: "/"
                backend:
                  service:
                    name: minio
                    port:
                      number: 9000
