name: ansiblecd

on:
  push:
    branches: [main, devel]
  pull_request:
    branches: [main, devel]

jobs:

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt -y install ansible
      - run: ansible-playbook -b --check --connection=local -i 127.0.0.1, workstation.yml
