name: ansiblecd

on:
  push:
    branches: [main, devel]

jobs:

  deploy_devel:
    runs-on: ubuntu-latest
    env:
      K8S_AUTH_KUBECONFIG: config.yaml
      K8S_AUTH_CONTEXT: devel
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt -y install ansible
      - run: pip install kubernetes
      - run: ansible-playbook --version
      - run: ansible-playbook devel.yaml
